name: "crypto_market_project"
version: "1.0.0"
config-version: 2

profile: "crypto_market_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_market_project:
    +on_schema_change: "append_new_columns"
    staging:
      +materialized: view
    marts:
      +materialized: table
